### PR TITLE
fix: NVME boot is only considered when network disconnected

### LINKED ISSUE #12: NVMe boot is broken
Due to the bootorder changes [here](https://github.com/siderolabs/sbc-raspberrypi/commit/da9bd8f040def6f35976fcf2ff2247de78c832a0#diff-d4f1821767b55a486069653d2b3bd380757228dbee6f912f2aa4bf0a21bb2c0bR23), NVMe is only considered when PXE/DHCP booting fails. In most scenarios, only if networking is disconnected.

### PR DESCRIPTION
**Pull request by xvzf**
Fixes #12 

Signed-off-by: Matthias Riegler <matthias.riegler@ankorstore.com>

### CODE REVIEW

**Review by frezbo — APPROVED** [review]
is this an upstream change?

**Comment by xvzf** [comment]
No, the upstream u-boot still does not enable NVMe boot by default [ref](https://github.com/u-boot/u-boot/blob/8937bb265a7f2251c1bd999784a4ef10e9c6080d/board/raspberrypi/rpi/rpi.env#L77).

The patch added in https://github.com/siderolabs/sbc-raspberrypi/commit/da9bd8f040def6f35976fcf2ff2247de78c832a0#diff-d4f1821767b55a486069653d2b3bd380757228dbee6f912f2aa4bf0a21bb2c0bR23 removed the patch I've initially pulled in from the homeassistant project, to enable NVMe booting on the CM4. They fixed it also by changing the order https://github.com/home-assistant/operating-system/blob/dev/buildroot-external/board/raspberrypi/patches/uboot/0002-rpi-add-NVMe-to-boot-order.patch

I'm happy to replace the initial patch by the one coming from home-assistant

**Comment by frezbo** [comment]
> No, the upstream u-boot still does not enable NVMe boot by default [ref](https://github.com/u-boot/u-boot/blob/8937bb265a7f2251c1bd999784a4ef10e9c6080d/board/raspberrypi/rpi/rpi.env#L77).
> 
> The patch added in [da9bd8f#diff-d4f1821767b55a486069653d2b3bd380757228dbee6f912f2aa4bf0a21bb2c0bR23](https://github.com/siderolabs/sbc-raspberrypi/commit/da9bd8f040def6f35976fcf2ff2247de78c832a0#diff-d4f1821767b55a486069653d2b3bd380757228dbee6f912f2aa4bf0a21bb2c0bR23) removed the patch I've initially pulled in from the homeassistant project, to enable NVMe booting on the CM4. They addressed this for u-boot 2024.01 by also by changing the order https://github.com/home-assistant/operating-system/blob/dev/buildroot-external/board/raspberrypi/patches/uboot/0002-rpi-add-NVMe-to-boot-order.patch
> 
> I'm happy to replace the initial patch by the one coming from home-assistant

let's pull in the one from home-assistant, so that we know the source

**Pull request merged**
